#testtest
#test2
# Starter pipelines
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- script: |
    echo INSTALLING gh
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
    sudo apt-add-repository https://cli.github.com/packages
    sudo apt update
    sudo apt install gh 
  displayName: 'INSTALLING gh'
  # specific branch

- script: |
    echo AUTHENTICATING gh
    $ curl -u satishgampala:c0bddb963d7c8c58175cc7585caaeb0c0466837a https://api.github.com/user
 #gh auth login --with-token c0bddb963d7c8c58175cc7585caaeb0c0466837a
    # gh repo fork satishgampala/dynamic-transcoder --remote=false
  displayName: 'AUTHENTICATE gh'

- task: GitHubComment@0
  inputs:
    gitHubConnection: 'Cndhunarala'
    repositoryName: 'Cndhunarala/Azurepolicy'
    id: '12'

