name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
#   pull_request:
#     branches:
#       - test
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: 4210b6a486304b159b7a3b70716e2d14aa902502
          commit-message: Update report
          branch: example-patches
         
# jobs:
#   createPullRequest:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v3
#         with:
#           commit-message: update 
#           token: 4210b6a486304b159b7a3b70716e2d14aa902502
#           branch: test
          
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
#     build:
#         name: Call Azure Pipeline
#         runs-on: ubuntu-latest
#         steps:
#         - name: Azure Pipelines Action
#           uses: Azure/pipelines@v1
#           with:
#             azure-devops-project-url: https://dev.azure.com/sindhunaralaiiitn/Testing2
#             azure-pipeline-name: 'Cndhunarala.Azurepolicy (1)'
#             azure-devops-token: ogky7tvdw5jsmbe2amik3dnmeqtio7igxj4ufc4bmf2tomowg3fa
