name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - test

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/sindhunaralaiiitn/Testing2
            azure-pipeline-name: 'Cndhunarala.Azurepolicy (1)'
            azure-devops-token: ogky7tvdw5jsmbe2amik3dnmeqtio7igxj4ufc4bmf2tomowg3fa
